---
title: "Main R Markdown Document For NCAA Basketball Analysis"
author: "Ben Wasserman and Connor Kennedy"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('tidyverse')
library('magrittr')
```

In this document we clean the data, join the day, add some columns, create factors, and provide some summary statistics around the data. We are  also interested in adding TV ratings and/or revenue to see how upsets and seasons affect TV ratings and revenue generated

```{r}
# get and set working directory

# read in files
tourney_games <- read.csv("ConferenceTourneyGames.csv")
tourney_compact_results <- read.csv("NCAATourneyCompactResults.csv")
regular_season_compact_results <- read.csv("RegularSeasonCompactResults.csv")
seasons <- read.csv("Seasons.csv")
team_coaches <- read.csv("TeamCoaches.csv")
teams <- read.csv("Teams.csv")
team_conferences <- read.csv("TeamConferences.csv")
tourney_seeds <- read.csv("NCAATourneySeeds.csv")
tourney_seeds_round_slots <- read.csv("NCAATourneySeedRoundSlots.csv")
tourney_detailed_result <- read.csv("NCAATourneyDetailedResults.csv")
tourney_slots <- read.csv("NCAATourneySlots.csv")
regular_season_detailed_result <- read.csv("RegularSeasonDetailedResults.csv")
rating_round_viewers <- read.csv("rating_round_viewers.csv")
```


```{r}
########### BELOW ARE A VARIETY OF DATA CLEANING AND FEATURE ENGINEERING ################
tourney_slots <- tourney_slots %>% rename(GameSlot = Slot)

View(rounds_df)
View(teams)

# merge rounds, teams, and seeds
rounds_df <- left_join(x = tourney_slots,
                       y = tourney_seeds_round_slots,
                       by = "GameSlot")

# reorder by column name
rounds_df <- rounds_df[c("Season", "GameSlot", "WeakSeed", "GameRound")]

# get rid of duplicates
rounds_df <- rounds_df[!duplicated(rounds_df[1:4]),]

# join by slot and season
rounds_df <- left_join(rounds_df, 
                       tourney_slots, 
                       by = c("GameSlot", "Season"))

# team conferences to tourney results
team_conferences <- team_conferences %>% rename(WTeamID = TeamID)

# join with conferences
tourney_detailed_result <- left_join(x = tourney_detailed_result,
                                     y = team_conferences, 
                                     by = c("WTeamID", "Season"))

team_conferences <- team_conferences %>% rename(LTeamID = WTeamID)

tourney_detailed_result <- left_join(x = tourney_detailed_result,
                                     y = team_conferences, 
                                     by = c("LTeamID", "Season"))

tourney_detailed_result <- tourney_detailed_result %>% rename(
  WTeamConf = ConfAbbrev.x,
  LTeamConf = ConfAbbrev.y 
)

# get rid of seeds prior to 2002 for consistency
tourney_seeds <- subset(tourney_seeds, Season > 2002)
tourney_seeds <- tourney_seeds %>% rename(WTeamID = TeamID)

tourney_detailed_result <-left_join(x = tourney_detailed_result,
                                    y = tourney_seeds,
                                    by = c("WTeamID", "Season"))

tourney_seeds <- tourney_seeds %>% rename(LTeamID = WTeamID)

tourney_detailed_result <-left_join(x = tourney_detailed_result,
                                    y = tourney_seeds,
                                    by = c("LTeamID", "Season"))

tourney_detailed_result <- tourney_detailed_result %>% rename(
  WTeamSeed = Seed.x,
  LTeamSeed = Seed.y
)


# now I'm going to look to make a model for lower team wins and higher team wins
tourney_detailed_result <- tourney_detailed_result %>% mutate(
  lower_team = pmin(WTeamID, LTeamID),
  higher_team = pmax(WTeamID, LTeamID),
  lower_team_won = ifelse(WTeamID == lower_team, 1, 0)
)

View(tourney_detailed_result)

# add team names
teams <- teams %>% select(TeamName, TeamID)
teams <- teams %>% rename(WTeamID = TeamID)
tourney_detailed_result <-left_join(x = tourney_detailed_result,
                                    y = teams,
                                    by = "WTeamID")

teams <- teams %>% rename(LTeamID = WTeamID)
tourney_detailed_result <- left_join(x = tourney_detailed_result,
                                     y = teams, 
                                     by = "LTeamID")

# need to change this to be mutated
#tourney_detailed_result[["WTeamID"]] <- teams[ match(tourney_detailed_result[['WTeamID']], teams[['TeamID']] ), 'TeamName']
#tourney_detailed_result[["LTeamID"]] <- teams[ match(tourney_detailed_result[['LTeamID']], teams[['TeamID']] ), 'TeamName']

# renaming
tourney_detailed_result %<>% rename(WTeamName = WTeamID,
                                    LTeamName = LTeamID)

# add score difference
tourney_detailed_result <- tourney_detailed_result %>% mutate(scoreDiff = WScore - LScore)


# add rounds to tourney_detailed_results
tourney_detailed_result <- tourney_detailed_result %>% mutate(Round = ifelse(
  DayNum %in% 134:135, 0,
  ifelse(DayNum %in% 136:137, 1,
         ifelse(DayNum %in% 138:139, 2,
                ifelse(DayNum %in% 143:144, 3,
                       ifelse(DayNum %in% 145:146, 4,
                              ifelse(DayNum == 152, 5,
                                     ifelse(DayNum == 154, 6, 7))))))
))

View(tourney_detailed_result)

View(rating_round_viewers)

# add TV ratings and viewers for championship games

rating_round_viewers %<>% rename(Round = ï..Round)
tourney_detailed_result <-left_join(x = tourney_detailed_result,
                                    y = rating_round_viewers,
                                    by = c("Season", "Round"))

# factoring 
tourney_detailed_result %<>% mutate(Season = factor(Season),
                                    DayNum = factor(DayNum),
                                    WTeamName = factor(WTeamName),
                                    LTeamName = factor(LTeamName),
                                    NumOT = factor(NumOT))

# make all the seeds only numeric
tourney_detailed_result$WTeamSeed <- as.integer(gsub('[a-zA-Z]', '',
                                                     tourney_detailed_result$WTeamSeed))
tourney_detailed_result$LTeamSeed <- as.integer(gsub('[a-zA-Z]', '',
                                                     tourney_detailed_result$LTeamSeed))


# transition all wins and losses into deltas
tourney_detailed_result <- tourney_detailed_result %>% mutate(
  DFTM = WFTM - LFTM,
  DStl = WStl - LStl,
  DFGA = WFGA - LFGA,
  DFGA3 = WFGA3 - LFGA3,
  DFGM3 = WFGM3 - LFGM3,
  DFTM = WFTM - LFTM,
  DFTA = WFTA - LFTA,
  DOR = WOR - LOR,
  DDR = WDR - LDR,
  DTO = WTO - LTO,
  DAst = WAst - LAst,
  DBlk = WBlk - LBlk,
  DPF = WPF - LPF
)

tourney_detailed_result <- tourney_detailed_result %>% select(
  DFTM, DStl, DFGA, DFGA3, DFGM3, DFTM, DFTA, DOR, DDR,
  DTO, DAst, Season, Round, WTeamName, LTeamName, WTeamConf,
  LTeamConf, scoreDiff, WTeamSeed, LTeamSeed, DBlk, DPF, lower_team,
  higher_team, lower_team_won 
)

View(tourney_detailed_result)

names(tourney_detailed_result)

# not super explainable for the data
mod1 <- lm(scoreDiff ~ WTeamConf + LTeamConf + 
             WTeamSeed + LTeamSeed + Round, data = tourney_detailed_result)

summary(mod1)

```


```{r}
# summary statistics
summary(tourney_detailed_result)

# wins per team
tourney_wins_per_team <- tourney_detailed_result %>% group_by(WTeamName) %>% 
  summarize(num_wins = n()) %>%
  arrange(desc(num_wins))
head(tourney_wins_per_team)

# wins per team per season
wins_per_team_per_season <- tourney_detailed_result %>% group_by(Season) %>% 
  count(WTeamName)
head(wins_per_team_per_season)

# summary details of score by seed
seed_details <- tourney_detailed_result %>% group_by(WTeamSeed) %>%
  summarize(avg_points_per_seed = mean(WScore),
            max_points_per_seed = max(WScore),
            min_points_per_seed = min(WScore))
seed_details

# summary details of score by conference
conf_details <- tourney_detailed_result %>% group_by(WTeamConf) %>%
  summarize(avg_points_per_conf = mean(WScore),
            max_points_per_conf = max(WScore),
            min_points_per_conf = min(WScore))
conf_details

# summary details of three points by season
three_pt_details <- tourney_detailed_result %>% group_by(Season) %>%
  summarize(avg_three_pts = mean(WFGM3),
            max_three_pts = max(WFGM3),
            min_three_pts = min(WFGM3))
three_pt_details

# summay details of field goals by season
field_goals_details <- tourney_detailed_result %>% group_by(Season) %>%
  summarize(avg_field_goals = mean(WFGM),
            max_field_goals = max(WFGM),
            min_field_foals = min(WFGM))
field_goals_details


# summary details of score by winning
winner_seed_details <- tourney_detailed_result %>% group_by(Season, WTeamSeed) %>%
  summarize(avg_points_per_WTeamSeed = mean(WScore),
            max_points_per_WTeamSeed = max(WScore),
            min_points_per_WTeamSeed = min(WScore))
winner_seed_details


```


```{r}
# plots to reveal interesting patterns

library('ggthemes')

tourney_detailed_result <- tourney_detailed_result %>% mutate(WTeamConfFactor = fct_lump(WTeamConf, 10))

# top ten conferences frequency of wins
p4 <- ggplot(tourney_detailed_result, aes(x=WTeamConfFactor)) +
  geom_bar() +
  labs(x = "Conference",
       title = "Frequency of Wins By Conference")

p4

# field goals made vs score difference
p1 <- ggplot(
  tourney_detailed_result,
  aes(x = WFGM, y = scoreDiff)) + 
  geom_point() +
  labs(x = "Field Goals Made",
       y = "Score Difference",
       title = "Score difference and field goals made") +
  theme_economist()
p1

# density plot by conference
library(ggridges)
p2 <- ggplot(tourney_detailed_result, aes(x = scoreDiff, y = WTeamConfFactor, fill = WTeamConfFactor)) +
  geom_density_ridges() + 
  labs(x = "Score Difference",
       y = "Winning Team Conference")

p2

# scatter plot of winning scores and conferences
p3 <- ggplot(tourney_detailed_result, aes(x = WScore, y = WTeamConfFactor)) +
  geom_point() + 
  labs(x = "Winning Score",
       y = "Winning Team Conference")
  
p3

# correlation plot of a variety of game stats
library(corrplot)
cormat <- cor(tourney_detailed_result %>% select(LScore, WScore,
                                                    WFGA, LFGA,
                                                 WAst, LAst, WFTM, LFTM, 
                                                    WFGM, LFGM) %>% drop_na())
corrplot(cormat, method = "number", type="lower")



```


```{r}
# intial models we may want to fit
# we should be looking to test against the regular season data and predict into the tournament data for each year - try and get win probabilities


# making winning binomial
tourney_detailed_result <- tourney_detailed_result %>% mutate(WBinom = rep(1))
mod1 <- glm(WBinom ~ LTeamName, 
            data = tourney_detailed_result)

```